# Generated by Django 5.2.8 on 2025-11-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_name', models.CharField()),
                ('status', models.CharField(choices=[('In_Transit', 'In Transit'), ('At_Warehouse', 'At warehouse'), ('Deliver', 'Out for Delivery'), ('Delivered', 'Delivered')], default='At_Warehouse')),
                ('assigned_driver', models.CharField()),
                ('tracking_ID', models.TextField()),
                ('destination', models.TextField()),
            ],
        ),
    ]
