# Generated by Django 6.0 on 2025-12-07 18:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='shipment_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('In_Transit', 'In Transit'), ('At_Warehouse', 'At warehouse'), ('Deliver', 'Out for Delivery'), ('Delivered', 'Delivered')], default='At_Warehouse', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='tracking_ID',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Tracking ID input invalid.', regex='^[A-Z0-9-]+$')]),
        ),
    ]
