# Generated by Django 6.0 on 2025-12-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipments_customer_alter_shipments_assigned_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='tracking_ID',
            new_name='tracking_id',
        ),
    ]
