FROM python:3.11-slim

WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt ./

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose port 8000


# Define environment variable
